- name: Add Kernel Modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  become: true
  with_items: 
    - "{{ kernel_modules }}"

- name: Copy sys control settings
  ansible.builtin.copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  register: sys_k8s
  become: true

- name: Run update when sys control settings changed
  ansible.builtin.command: sysctl --system
  become: true
  when: sys_k8s.changed
    

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    update_cache: yes
  become: true
  register: containerd_installed

- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
  register: cd_containerd
  become: true

- name: Create default config
  ansible.builtin.shell:
    sudo containerd config default | sudo tee /etc/containerd/config.toml
  when: containerd_installed.changed

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
  become: true
  when: containerd_installed.changed

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a
  when: containerd_installed.changed
  become: true

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: containerd_installed.changed
  become: true

- name: Install Kubernetes recommended packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - curl
    - apt-transport-https
    - gpg
  become: true

- name: Add K8S GPG Key
  ansible.builtin.shell:
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args: 
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: keyring_added

- name: Copy k8s debian repo src
  ansible.builtin.copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
  become: true

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install k8s modules
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ k8s_tools }}"
  become: true